CREATE TABLE urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url VARCHAR(2048) NOT NULL,
    short_code VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    access_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_urls_short_code UNIQUE (short_code)
);

CREATE INDEX idx_urls_short_code ON urls (short_code);
