spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/topaz
    driver-class-name: org.postgresql.Driver
    username: topaz
    password: topaz
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
